### ISSUE TITLE
Submission Checklist

### ISSUE THREAD

**Issue by ninjaNgai** [rviccina/TigerGraphHackathon#12]
[Submission rules](https://tigergraph2020.devpost.com/rules)

**Required**
- [ ] Create a video that includes footage that clearly explains your application’s features and functionality through a comprehensive demonstration.
- [ ] Share the URL to functional application on the web or in an App Store
- [ ] Share link to public code repository (#8)
- [ ] Complete and enter all of the required fields on the “Enter a Submission” page of the Hackathon Website (each a “Submission”) during the Hackathon Submission Period, and follow the requirements below.

**Optional**
- [ ] Share link to your optional Medium Blog, supporting the project

https://tigergraph2020.devpost.com/
1. Create a video walkthrough - a minimum of 2 minutes
2. Share source code on GitHub - Include a link to the repository
2a. Tag GitHub Repository - with TigerGraph
2b. Have Documentation
